apiVersion: apps/v1
kind: Deployment

metadata:
  name: devsecops-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devsecops-demo

  template:
    metadata:
      labels:
        app: devsecops-demo

    spec:
      containers:
      - name: devsecops-demo
        image: vedasamhitha17/devsecops-demo:latest   # FIXED
        ports:
        - containerPort: 8082
