apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
spec:
  selector:
    app: devsecops-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 31080
